sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: rAtJ9vBxU2JAOGtBB59AtTNnzIibUFwm6+6TcRqG4xhpl2BMJRvYLcZmy0A0SMdNXV6m9uSX3Sfs5Y5yGH1wYPJJMohF6+mAmxbMQ8QnWlMH9DuvoZcGz4BZsEe61EVekr2GwawHHfxkSKG9fW6YEiK0niHTgf815MR3sLvtuI1SIfx4+Yv47db6SIiwJDrpk9SRlHOR5miC0WaUl5DPFePfTYArJ1mIoiWADS8gWszUnbLaby97LU4fkYgPlawzMy81ZJcQzpa17zTdtzao87Hg0GW9zaLd3uSXw/BtyX4JlHlZeBoCDWTXiH8Bw6Plt3AF1AnchKgXFM/k/brK1IKZQjvQbhV3FFfzn5SeLQcdfKb74UGju16xM1oX1mb32lCTyGwmc/Q3e2pu37c46fmxC6njvOr+7iPdAxqRtZPROBxW1s2i+vGPnx3hptDq/d27zaWxJ9VUuOJZukbbem3f7DLz8Y88dogHyHqGXC0CCAxxJZNNllMjpuWVE8l8SZhb706JAJaEDoOWhb91SqRKC1z/Cd3oa6YYPan67+fQ4RDCFUe3MktX1xIqmSyj0ep4gdTnr1HTiCNBUxQezt4+AUt/PwQVL5CvPIeronKtALoBMJGD+kWGj3muI3iRHawnm0C5tpiDfCetqgMkEfPydDrrwgcfZb79Fka9pvk=
branches:
  only:
  - master
