sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2
install:
- bundle install
script: bundle exec rake site:deploy --quiet
env:
  global:
    secure: i1BZPQ+Bpd7tK7j97qNFK5zEYFwEuK8ybpxm/BCzHInx42yQIDd4SvHHRFkY6tXNVfcHeNK7AAxio+4fsmsEnhS79payYle1D2f7YWy3mympH/EGnJ/TT4jVGkgGY+QPgOlnpiv/JsFzrYtgfpLZvFjE/zDk1ah+NW5/rKVo0MAaPCLJ9WZU9CxHLVPNy5KKxOMXl9F1l8vVzXHkv0N5oh605KP4O7Nvl4p6AQFHp2Qu3HgJNydh6wz6I4Grl3s5PZgtdWt3vEmtDdkPJDseOI/fceZ0HJ4L0iaDxUGZl05EhD+vfy5Lt1IElIGV4TjHBfRxqswA4Xr2MoReAeEjJVZPAEnQ/oni3YQOTdW0Zi1/wnj03Kp2tbNZuBI0F5fChKTE+XYhedls7CksEuvbMsgGdphX8jpBt1wa61MeBemJjC/Zywe6ddlzbL+9FfP9PIgb0N2p6y06rO2xx3n0NZ+HEFpZN6JOIzM4dHDRzymtxJHEmGtPY1MpgId9uUSAIEZSfzjh7ogOsq2sDtO4W7kE2rlWp8N90FGLc9yk8mqCD8iRBMdh0BGQYhyzPFztxK39eTVhHi+NS51EDbJTMowqyncywfl0UJFEloLooGFb5yXlZQJEyPrhIf5XiDr+su2MS6JC5YaPxeX2mZ1IU+F0/EoIOVCdaqIk3arz9R8=
branches:
  only:
  - master
